### ISSUE TITLE
Existing simulations

### ISSUE THREAD

**Issue by ccluri** [OpenSourceBrain/Thalamocortical#14]
FYI : Some simulations of the Traub's model, are available [here](http://dx.doi.org/10.18150/repod.6394793)

A full in-depth details of these simulations have been submitted as a data article and is under review.

**Comment by pgleeson** [comment]
Thanks for this @ccluri, I've added a link to this dataset to the wiki [here](http://www.opensourcebrain.org/projects/thalamocortical/wiki/Known_issues).

**Comment by ccluri** [comment]
Now available as a well documented, peer reviewed data article https://link.springer.com/article/10.1007/s12021-016-9319-4  :)
